{% set build = 0 %}
{% set name = "shenfun" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/shenfun/archive/{{ version }}.tar.gz
  sha256: c1e0d0f3f3a66105e11d46e4d5ccc2d85a0d1c5c80ab44fec6e2c2cfb376d81e

build:
  number: {{ build }}
  skip: true  # [win]
  script:
    - export OPAL_PREFIX=$PREFIX   # [mpi == "openmpi"]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - numpy
    - setuptools
    - python
    - cython
    - fftw
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - fftw
    - mpi4py
    - mpi4py-fft >=2.0.3
    - sympy
    - hdf5 * mpi_*  # [py>36]
    - h5py * mpi_*  # [py>36]
    - netcdf4 * mpi_*

test:
  commands:
    - |
    - export OMPI_MCA_plm=isolated                          # [mpi == "openmpi"]
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [mpi == "openmpi"]
    - export OMPI_MCA_rmaps_base_oversubscribe=yes          # [mpi == "openmpi"]
    - export OMPI_ALLOW_RUN_AS_ROOT=1                       # [mpi == "openmpi"]
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1               # [mpi == "openmpi"]

    - python -c "import shenfun"

about:
  home: https://github.com/spectralDNS/shenfun
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: High performance computational platform for the spectral Galerkin method
  description: |
    Shenfun is a high performance computing platform for solving partial
    differential equations (PDEs) by the spectral Galerkin method. The platform
    can be used for any PDE, but applications are limited to multidimensional
    tensor product grids. The code is parallelized with MPI through the
    mpi4py-fft package.
  doc_url: https://shenfun.readthedocs.io
  dev_url: https://github.com/spectralDNS/shenfun

extra:
  recipe-maintainers:
    - mikaem
