{% set build = 0 %}
{% set name = "shenfun" %}
{% set version = "3.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/shenfun/archive/{{ version }}.tar.gz
  sha256: 128cff375a72d60a317d3deff5af2a1efe5b7a2ffd4bdaee38ffc32914cef22a

build:
  number: {{ build }}
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - setuptools
    - python
    - cython
    - fftw
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - fftw
    - mpi4py
    - mpi4py-fft >=2.0.3
    - sympy
    - hdf5 * mpi_*
    - h5py * mpi_*
    - netcdf4 * mpi_*

about:
  home: https://github.com/spectralDNS/shenfun
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: High performance computational platform for the spectral Galerkin method
  description: |
    Shenfun is a high performance computing platform for solving partial
    differential equations (PDEs) by the spectral Galerkin method. The platform
    can be used for any PDE, but applications are limited to multidimensional
    tensor product grids. The code is parallelized with MPI through the
    mpi4py-fft package.
  doc_url: https://shenfun.readthedocs.io
  dev_url: https://github.com/spectralDNS/shenfun

extra:
  recipe-maintainers:
    - mikaem
