{% set build = 2 %}
{% set name = "shenfun" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/shenfun/archive/{{ version }}.tar.gz
  sha256: 4edd0a2202b9af30ab8f734c1bcf8d9fb1c7b33ac02b00b298e730e53d136544

build:
  number: {{ build }}
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - setuptools
    - python
    - cython
    - fftw
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - fftw
    - mpi4py
    - mpi4py-fft >=2.0.3
    - sympy
    - hdf5 * mpi_* # [py>36]
    - h5py * mpi_* # [py>36]
    - netcdf4 * mpi_*

about:
  home: https://github.com/spectralDNS/shenfun
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: High performance computational platform for the spectral Galerkin method
  description: |
    Shenfun is a high performance computing platform for solving partial
    differential equations (PDEs) by the spectral Galerkin method. The platform
    can be used for any PDE, but applications are limited to multidimensional
    tensor product grids. The code is parallelized with MPI through the
    mpi4py-fft package.
  doc_url: https://shenfun.readthedocs.io
  dev_url: https://github.com/spectralDNS/shenfun

extra:
  recipe-maintainers:
    - mikaem
