{% set build = 2 %}
{% set name = "shenfun" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spectralDNS/shenfun/archive/{{ version }}.tar.gz
  sha256: fe0e7aa9abc4ea23a4ebd2b7f6b4c5ff4dfb124ef79603393a8ffbb470c62478

build:
  number: {{ build }}
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - numpy                               # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cython <3.0                         # [build_platform != target_platform]
    - fftw                                # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - setuptools
    - python
    - cython <3.0
    - fftw
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pyyaml
    - fftw
    - mpi4py
    - mpi4py-fft >=2.0.5
    - mpich
    - sympy
    - hdf5 * mpi_*
    - h5py * mpi_*
    - netcdf4 * mpi_*

about:
  home: https://github.com/spectralDNS/shenfun
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: High performance computational platform for the spectral Galerkin method
  description: |
    Shenfun is a high performance computing platform for solving partial
    differential equations (PDEs) by the spectral Galerkin method. The platform
    can be used for any PDE, but applications are limited to multidimensional
    tensor product grids. The code is parallelized with MPI through the
    mpi4py-fft package.
  doc_url: https://shenfun.readthedocs.io
  dev_url: https://github.com/spectralDNS/shenfun

extra:
  recipe-maintainers:
    - mikaem
