travis:
  secure:
    BINSTAR_TOKEN: K1lpLjcdjdLVi2He3C+UXPQaUtNjTNqk+KRragnrhyrSw9ihgBIfysooEJygCqKo9rl2/dnAFQJzedeZcqcFtFVevN2U+qaJq8pfDm4yPWSEnGD+QKf/JF71munsuzoHsljeO93imw5o0O2egUVr/XBkg8r5DhShAnCYxEvMLcIWE8rrOklgz4I6Tzbe7J+2QuVP8SFviYhiwtN3n5IHjndiYoKvQIT477pbPgABPC7FPIDv8x92d7uJfzeWo0WL/T4zoh4SaNaSoKKNx+wQMaP7fnFR/6djh3bPIgGAZUf3u6A2hsM3c/DvnadiUZCYPki/bsO9eleVHFy9INFHbK6lT6Z+yIKVkxIGOS3JBp2LIsCTCgKWx3z4AdoKwfyxgXdSBI0r5pCk+M7HbYljoxYW0ezqozPm1OCOAZfo8QtAyEBrt9iosU62FjfX5uXS8CPw8yWR23QV34K1pwbgoF0LZAA9WNR5meMH6pl+FE5e80T4pEu4A5i0jiTVQyXX3j/G+DM5QMsohzCf7UsFgMG+CxMUrKBny/By8540zTBAespl1KQzAo5hZA0guGmV0wwT47uvxyhxgNRTg3vyyZbvex2TtZIdiM0942O7w/Qzf0dzI9hcqHluxGwhO/S0FujHHRgIk/CIPwGZUFp0MK+yZR8BC0apqE9dX4d5C88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
